version: "3.9"
services:
  database:
    image: mysql
    # This line of code ensures that password authentication is the default authentication method used to connect to the database:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: aspnetapp
    ports:
      - "3306:3306/tcp"
