version: '3.9'
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: aspnetapp
    ports:
      - '3306:3306/tcp'
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite-blob --blobHost 0.0.0.0
    ports:
      - '10000:10000/tcp'
  aspnetapp:
    build: .
    image: registry.digitalocean.com/shertu/aspnetapp_aspnetapp
    ports:
      - '5001:443/tcp'
      - '5000:80/tcp'
