// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zukte.Database;

namespace zukte.Migrations;
[DbContext(typeof(ApplicationDbContext))]
[Migration("20210218114626_InitialCreate")]
partial class InitialCreate {
  protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
    modelBuilder
        .HasAnnotation("Relational:MaxIdentifierLength", 64)
        .HasAnnotation("ProductVersion", "5.0.2");

    modelBuilder.Entity("Zukte.Message.ApplicationUser.ApplicationUser", b => {
      b.Property<string>("Id")
          .HasColumnType("varchar(767)");

      b.Property<string>("Name")
          .HasColumnType("text");

      b.Property<string>("Picture")
          .HasColumnType("text");

      b.HasKey("Id");

      b.ToTable("ApplicationUsers");
    });
#pragma warning restore 612, 618
  }
}

