// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protobuf/application_user_list_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zukte.Message.ApplicationUser {

  /// <summary>Holder for reflection information generated from protobuf/application_user_list_request.proto</summary>
  public static partial class ApplicationUserListRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for protobuf/application_user_list_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ApplicationUserListRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cixwcm90b2J1Zi9hcHBsaWNhdGlvbl91c2VyX2xpc3RfcmVxdWVzdC5wcm90",
            "bxIdWnVrdGUuTWVzc2FnZS5BcHBsaWNhdGlvblVzZXIaH3Byb3RvYnVmL2Fw",
            "cGxpY2F0aW9uX3VzZXIucHJvdG8i1gEKGkFwcGxpY2F0aW9uVXNlckxpc3RS",
            "ZXF1ZXN0EhIKCnBhZ2VfdG9rZW4YASABKAkSEwoLbWF4X3Jlc3VsdHMYAiAB",
            "KA0SCgoCaWQYAyABKAkSDAoEbWluZRgEIAEoCBp1ChtBcHBsaWNhdGlvblVz",
            "ZXJMaXN0UmVzcG9uc2USPQoFaXRlbXMYASADKAsyLi5adWt0ZS5NZXNzYWdl",
            "LkFwcGxpY2F0aW9uVXNlci5BcHBsaWNhdGlvblVzZXISFwoPbmV4dF9wYWdl",
            "X3Rva2VuGAIgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zukte.Message.ApplicationUser.ApplicationUserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zukte.Message.ApplicationUser.ApplicationUserListRequest), global::Zukte.Message.ApplicationUser.ApplicationUserListRequest.Parser, new[]{ "PageToken", "MaxResults", "Id", "Mine" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Zukte.Message.ApplicationUser.ApplicationUserListRequest.Types.ApplicationUserListResponse), global::Zukte.Message.ApplicationUser.ApplicationUserListRequest.Types.ApplicationUserListResponse.Parser, new[]{ "Items", "NextPageToken" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// represents a query for some user accounts 
  /// </summary>
  public sealed partial class ApplicationUserListRequest : pb::IMessage<ApplicationUserListRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ApplicationUserListRequest> _parser = new pb::MessageParser<ApplicationUserListRequest>(() => new ApplicationUserListRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ApplicationUserListRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zukte.Message.ApplicationUser.ApplicationUserListRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApplicationUserListRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApplicationUserListRequest(ApplicationUserListRequest other) : this() {
      pageToken_ = other.pageToken_;
      maxResults_ = other.maxResults_;
      id_ = other.id_;
      mine_ = other.mine_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ApplicationUserListRequest Clone() {
      return new ApplicationUserListRequest(this);
    }

    /// <summary>Field number for the "page_token" field.</summary>
    public const int PageTokenFieldNumber = 1;
    private string pageToken_ = "";
    /// <summary>
    /// a seek pagination token
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PageToken {
      get { return pageToken_; }
      set {
        pageToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "max_results" field.</summary>
    public const int MaxResultsFieldNumber = 2;
    private uint maxResults_;
    /// <summary>
    /// a pagination size limiter
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint MaxResults {
      get { return maxResults_; }
      set {
        maxResults_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 3;
    private string id_ = "";
    /// <summary>
    /// a filter used to select user accounts with the specified ids
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mine" field.</summary>
    public const int MineFieldNumber = 4;
    private bool mine_;
    /// <summary>
    /// a filter used to select user accounts associated with an authenticated user
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Mine {
      get { return mine_; }
      set {
        mine_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ApplicationUserListRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ApplicationUserListRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PageToken != other.PageToken) return false;
      if (MaxResults != other.MaxResults) return false;
      if (Id != other.Id) return false;
      if (Mine != other.Mine) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PageToken.Length != 0) hash ^= PageToken.GetHashCode();
      if (MaxResults != 0) hash ^= MaxResults.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Mine != false) hash ^= Mine.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PageToken.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PageToken);
      }
      if (MaxResults != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(MaxResults);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Id);
      }
      if (Mine != false) {
        output.WriteRawTag(32);
        output.WriteBool(Mine);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PageToken.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PageToken);
      }
      if (MaxResults != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(MaxResults);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Id);
      }
      if (Mine != false) {
        output.WriteRawTag(32);
        output.WriteBool(Mine);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PageToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PageToken);
      }
      if (MaxResults != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxResults);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Mine != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ApplicationUserListRequest other) {
      if (other == null) {
        return;
      }
      if (other.PageToken.Length != 0) {
        PageToken = other.PageToken;
      }
      if (other.MaxResults != 0) {
        MaxResults = other.MaxResults;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Mine != false) {
        Mine = other.Mine;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PageToken = input.ReadString();
            break;
          }
          case 16: {
            MaxResults = input.ReadUInt32();
            break;
          }
          case 26: {
            Id = input.ReadString();
            break;
          }
          case 32: {
            Mine = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PageToken = input.ReadString();
            break;
          }
          case 16: {
            MaxResults = input.ReadUInt32();
            break;
          }
          case 26: {
            Id = input.ReadString();
            break;
          }
          case 32: {
            Mine = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ApplicationUserListRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class ApplicationUserListResponse : pb::IMessage<ApplicationUserListResponse>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ApplicationUserListResponse> _parser = new pb::MessageParser<ApplicationUserListResponse>(() => new ApplicationUserListResponse());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<ApplicationUserListResponse> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Zukte.Message.ApplicationUser.ApplicationUserListRequest.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ApplicationUserListResponse() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ApplicationUserListResponse(ApplicationUserListResponse other) : this() {
          items_ = other.items_.Clone();
          nextPageToken_ = other.nextPageToken_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ApplicationUserListResponse Clone() {
          return new ApplicationUserListResponse(this);
        }

        /// <summary>Field number for the "items" field.</summary>
        public const int ItemsFieldNumber = 1;
        private static readonly pb::FieldCodec<global::Zukte.Message.ApplicationUser.ApplicationUser> _repeated_items_codec
            = pb::FieldCodec.ForMessage(10, global::Zukte.Message.ApplicationUser.ApplicationUser.Parser);
        private readonly pbc::RepeatedField<global::Zukte.Message.ApplicationUser.ApplicationUser> items_ = new pbc::RepeatedField<global::Zukte.Message.ApplicationUser.ApplicationUser>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::Zukte.Message.ApplicationUser.ApplicationUser> Items {
          get { return items_; }
        }

        /// <summary>Field number for the "next_page_token" field.</summary>
        public const int NextPageTokenFieldNumber = 2;
        private string nextPageToken_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string NextPageToken {
          get { return nextPageToken_; }
          set {
            nextPageToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as ApplicationUserListResponse);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(ApplicationUserListResponse other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if(!items_.Equals(other.items_)) return false;
          if (NextPageToken != other.NextPageToken) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          hash ^= items_.GetHashCode();
          if (NextPageToken.Length != 0) hash ^= NextPageToken.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          items_.WriteTo(output, _repeated_items_codec);
          if (NextPageToken.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(NextPageToken);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          items_.WriteTo(ref output, _repeated_items_codec);
          if (NextPageToken.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(NextPageToken);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          size += items_.CalculateSize(_repeated_items_codec);
          if (NextPageToken.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(NextPageToken);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(ApplicationUserListResponse other) {
          if (other == null) {
            return;
          }
          items_.Add(other.items_);
          if (other.NextPageToken.Length != 0) {
            NextPageToken = other.NextPageToken;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                items_.AddEntriesFrom(input, _repeated_items_codec);
                break;
              }
              case 18: {
                NextPageToken = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                items_.AddEntriesFrom(ref input, _repeated_items_codec);
                break;
              }
              case 18: {
                NextPageToken = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
